"""empty message

Revision ID: 153f44e875d6
Revises: 2d1a53994374
Create Date: 2021-03-28 22:34:25.698550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153f44e875d6'
down_revision = '2d1a53994374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
