"""empty message

Revision ID: 87126d6046eb
Revises: acae7d361681
Create Date: 2021-03-28 22:29:53.890642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87126d6046eb'
down_revision = 'acae7d361681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
